# Generated by Django 2.2.16 on 2022-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220715_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка прикрепленная к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
