# Generated by Django 2.2.16 on 2022-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220715_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка прикрепленная к посту', upload_to='posts/images/', verbose_name='Картинка'),
        ),
    ]
