# Generated by Django 2.2.16 on 2022-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20220801_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', help_text='Выберете картинку для аватара', upload_to='posts/avatar', verbose_name='Аватар'),
        ),
    ]
