# Generated by Django 2.2.16 on 2022-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220803_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Аватар', 'verbose_name_plural': 'Аватар'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', help_text='Выберете картинку для аватара', upload_to='posts/avatar', verbose_name='avatar'),
        ),
    ]
