# Generated by Django 2.2.16 on 2022-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220803_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', help_text='Выберете картинку для аватара', upload_to='posts/avatar', verbose_name='Аватар'),
        ),
    ]
